### ISSUE TITLE
Thruster doesn't collide with terrain except for bottom connection point

### ISSUE THREAD

**Issue by BrennanStein** [BrennanStein/Procelio-Issues#13]
![image](https://cloud.githubusercontent.com/assets/23182254/22453037/9b54a31c-e730-11e6-8b84-906b104c364f.png)
(Cannot drive any farther forwards)

Likely reason for bug:
     - Game doesn't check collision of laser collider model.
     - Only bottom connection point is actually a valid attachment; this connection is what collides.

Edit: Likely the same root cause as with the wheels clipping sideways into terrain.

**Comment by robot-rover** [comment]
This is because the colliders are trigger colliders in drive mode and I forgot to change it back with the laser and thruster. Will fix tonight.

**Comment by BrennanStein** [comment]
Appears to be fixed.
