### ISSUE TITLE
Bot position/rotation not always updated properly when exiting drive mode

### ISSUE THREAD

**Issue by BrennanStein** [BrennanStein/Procelio-Issues#5]

**Comment by robot-rover** [comment]
Haven't been able to reproduce...

**Comment by BrennanStein** [comment]
![image](https://cloud.githubusercontent.com/assets/23182254/22453553/797223ec-e734-11e6-89e6-94eca70fdc77.png)
Original report was from the discord chat, but I just had this happen

**Comment by BrennanStein** [comment]
![image](https://cloud.githubusercontent.com/assets/23182254/22497008/30cb7574-e803-11e6-8ed0-d4c3cbc5ed2a.png)
Wheels aren't reset, bot isn't grid-aligned. Newest push.

**Comment by robot-rover** [comment]
Grid align has been fixed. Due to bug with nav mesh agent moving a bit when its created.
